"""adiciona mais colunas em OS

Revision ID: 0bafd944816a
Revises: 489fb9a31985
Create Date: 2026-06-05 14:25:51.512273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bafd944816a'
down_revision: Union[str, Sequence[str], None] = '489fb9a31985'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes_pf', schema=None) as batch_op:
        batch_op.alter_column('cpf',
               existing_type=sa.VARCHAR(length=11),
               nullable=True)

    with op.batch_alter_table('clientes_pj', schema=None) as batch_op:
        batch_op.alter_column('cnpj',
               existing_type=sa.VARCHAR(length=14),
               nullable=True)
        batch_op.alter_column('nome_fantasia',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('ordem_servico_pagamentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vencimento', sa.Date(), nullable=True))

    with op.batch_alter_table('ordens_servico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credito_anterior', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordens_servico', schema=None) as batch_op:
        batch_op.drop_column('credito_anterior')

    with op.batch_alter_table('ordem_servico_pagamentos', schema=None) as batch_op:
        batch_op.drop_column('vencimento')

    with op.batch_alter_table('clientes_pj', schema=None) as batch_op:
        batch_op.alter_column('nome_fantasia',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('cnpj',
               existing_type=sa.VARCHAR(length=14),
               nullable=False)

    with op.batch_alter_table('clientes_pf', schema=None) as batch_op:
        batch_op.alter_column('cpf',
               existing_type=sa.VARCHAR(length=11),
               nullable=False)

    # ### end Alembic commands ###
