"""adiciona colunas na tabela de OS

Revision ID: 489fb9a31985
Revises: 95cf25d1ca1f
Create Date: 2026-06-03 16:24:52.107754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '489fb9a31985'
down_revision: Union[str, Sequence[str], None] = '95cf25d1ca1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracoes_clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('exigir_cpf_pf', sa.Boolean(), nullable=False),
    sa.Column('exigir_cnpj_pj', sa.Boolean(), nullable=False),
    sa.Column('exigir_celular', sa.Boolean(), nullable=False),
    sa.Column('exigir_rg_pf', sa.Boolean(), nullable=False),
    sa.Column('exigir_ie_pj', sa.Boolean(), nullable=False),
    sa.Column('exigir_email', sa.Boolean(), nullable=False),
    sa.Column('exigir_endereco', sa.Boolean(), nullable=False),
    sa.Column('tipo_pessoa_padrao', sa.String(length=2), nullable=False),
    sa.Column('exibir_genero', sa.Boolean(), nullable=False),
    sa.Column('exibir_data_nascimento', sa.Boolean(), nullable=False),
    sa.Column('bloquear_faturamento_inativo', sa.Boolean(), nullable=False),
    sa.Column('oferecer_reativacao_rapida', sa.Boolean(), nullable=False),
    sa.Column('ativar_limite_credito', sa.Boolean(), nullable=False),
    sa.Column('bloquear_venda_limite', sa.Boolean(), nullable=False),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id')
    )
    with op.batch_alter_table('configuracoes_clientes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_configuracoes_clientes_id'), ['id'], unique=False)

    op.create_table('configuracoes_produtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('exigir_codigo_barras', sa.Boolean(), nullable=False),
    sa.Column('exigir_categoria', sa.Boolean(), nullable=False),
    sa.Column('exigir_preco_custo', sa.Boolean(), nullable=False),
    sa.Column('margem_lucro_padrao', sa.Float(), nullable=False),
    sa.Column('utilizar_preco_atacado', sa.Boolean(), nullable=False),
    sa.Column('permitir_venda_estoque_zerado', sa.Boolean(), nullable=False),
    sa.Column('quantidade_minima_padrao', sa.Integer(), nullable=False),
    sa.Column('unidade_medida_padrao', sa.String(length=10), nullable=False),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id')
    )
    with op.batch_alter_table('configuracoes_produtos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_configuracoes_produtos_id'), ['id'], unique=False)

    with op.batch_alter_table('movimentacoes_estoque', schema=None) as batch_op:
        batch_op.alter_column('tipo',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.Enum('ENTRADA', 'SAIDA', 'AJUSTE', 'EDICAO_DADOS', name='movimentacaotipo'),
               existing_nullable=False)

    with op.batch_alter_table('ordens_servico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('situacao_equipamento', sa.Enum('REPARADO', 'SEM_REPARO', 'CONDENADO', name='situacaoequipamento'), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordens_servico', schema=None) as batch_op:
        batch_op.drop_column('situacao_equipamento')

    with op.batch_alter_table('movimentacoes_estoque', schema=None) as batch_op:
        batch_op.alter_column('tipo',
               existing_type=sa.Enum('ENTRADA', 'SAIDA', 'AJUSTE', 'EDICAO_DADOS', name='movimentacaotipo'),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False)

    with op.batch_alter_table('configuracoes_produtos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_configuracoes_produtos_id'))

    op.drop_table('configuracoes_produtos')
    with op.batch_alter_table('configuracoes_clientes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_configuracoes_clientes_id'))

    op.drop_table('configuracoes_clientes')
    # ### end Alembic commands ###
