"""initial_schema

Revision ID: 51db61228566
Revises: 
Create Date: 2026-06-05 17:28:54.853929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51db61228566'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movimentacoes_estoque', schema=None) as batch_op:
        batch_op.alter_column('tipo',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.Enum('ENTRADA', 'SAIDA', 'AJUSTE', 'EDICAO_DADOS', name='movimentacaotipo'),
               existing_nullable=False)

    with op.batch_alter_table('ordens_servico', schema=None) as batch_op:
        batch_op.alter_column('situacao_equipamento',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('REPARADO', 'SEM_REPARO', 'CONDENADO', name='situacaoequipamento'),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))

    with op.batch_alter_table('pagamentos_venda', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pagamentos_venda_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pagamentos_venda_venda_id'), ['venda_id'], unique=False)

    with op.batch_alter_table('vendas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendas_numero_venda'))
        batch_op.drop_column('numero_venda')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numero_venda', sa.INTEGER(), nullable=True))
        batch_op.create_index(batch_op.f('ix_vendas_numero_venda'), ['numero_venda'], unique=1)

    with op.batch_alter_table('pagamentos_venda', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pagamentos_venda_venda_id'))
        batch_op.drop_index(batch_op.f('ix_pagamentos_venda_id'))

    with op.batch_alter_table('ordens_servico', schema=None) as batch_op:
        batch_op.alter_column('situacao_equipamento',
               existing_type=sa.Enum('REPARADO', 'SEM_REPARO', 'CONDENADO', name='situacaoequipamento'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))

    with op.batch_alter_table('movimentacoes_estoque', schema=None) as batch_op:
        batch_op.alter_column('tipo',
               existing_type=sa.Enum('ENTRADA', 'SAIDA', 'AJUSTE', 'EDICAO_DADOS', name='movimentacaotipo'),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False)

    # ### end Alembic commands ###
