"""new tables for sales modules

Revision ID: 5cf42db01be6
Revises: 
Create Date: 2026-04-12 12:02:34.361779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cf42db01be6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessao_caixa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('funcionario_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ABERTO', 'FECHADO', name='sessaocaixastatus'), nullable=False),
    sa.Column('saldo_inicial', sa.Integer(), nullable=False),
    sa.Column('saldo_final_esperado', sa.Integer(), nullable=True),
    sa.Column('data_abertura', sa.DateTime(), nullable=False),
    sa.Column('data_fechamento', sa.DateTime(), nullable=True),
    sa.CheckConstraint('saldo_inicial >= 0', name='ck_sessao_caixa_saldo_inicial_nao_negativo'),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessao_caixa', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessao_caixa_funcionario_id'), ['funcionario_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessao_caixa_id'), ['id'], unique=False)

    op.create_table('vendas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('funcionario_id', sa.Integer(), nullable=False),
    sa.Column('sessao_caixa_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('RASCUNHO', 'CONCLUIDA', 'CANCELADA', name='vendastatus'), nullable=False),
    sa.Column('observacao', sa.String(length=500), nullable=True),
    sa.Column('subtotal', sa.Integer(), nullable=False),
    sa.Column('desconto', sa.Integer(), nullable=False),
    sa.Column('entrega', sa.Integer(), nullable=False),
    sa.Column('adiantamento', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.CheckConstraint('adiantamento >= 0', name='ck_venda_adiantamento_nao_negativo'),
    sa.CheckConstraint('desconto >= 0', name='ck_venda_desconto_nao_negativo'),
    sa.CheckConstraint('entrega >= 0', name='ck_venda_entrega_nao_negativo'),
    sa.CheckConstraint('subtotal >= 0', name='ck_venda_subtotal_nao_negativo'),
    sa.CheckConstraint('total >= 0', name='ck_venda_total_nao_negativo'),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionarios.id'], ),
    sa.ForeignKeyConstraint(['sessao_caixa_id'], ['sessao_caixa.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vendas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vendas_cliente_id'), ['cliente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vendas_funcionario_id'), ['funcionario_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vendas_id'), ['id'], unique=False)

    op.create_table('logs_produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('venda_id', sa.Integer(), nullable=True),
    sa.Column('funcionario_id', sa.Integer(), nullable=False),
    sa.Column('tipo_transacao', sa.Enum('ENTRADA', 'SAIDA_VENDA', 'ESTORNO', name='tipotransacaoestoque'), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('data_registro', sa.DateTime(), nullable=False),
    sa.CheckConstraint("(tipo_transacao == 'ENTRADA') OR (venda_id IS NOT NULL)", name='ck_log_produto_tipo_transacao_valida'),
    sa.CheckConstraint('quantidade != 0', name='ck_log_produto_quantidade_nao_zero'),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionarios.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['venda_id'], ['vendas.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('logs_produto', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_logs_produto_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_logs_produto_produto_id'), ['produto_id'], unique=False)

    op.create_table('pagamentos_venda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venda_id', sa.Integer(), nullable=False),
    sa.Column('forma_pagamento_id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Integer(), nullable=False),
    sa.Column('parcelado', sa.Boolean(), nullable=True),
    sa.Column('qtd_parcelas', sa.Integer(), nullable=True),
    sa.Column('data_pagamento', sa.DateTime(), nullable=False),
    sa.CheckConstraint('(parcelado IS NOT NULL) AND (qtd_parcelas >= 1)', name='ck_pagamento_venda_parcelas_min_1'),
    sa.CheckConstraint('valor > 0', name='ck_pagamento_venda_valor_positivo'),
    sa.ForeignKeyConstraint(['forma_pagamento_id'], ['formas_pagamento.id'], ),
    sa.ForeignKeyConstraint(['venda_id'], ['vendas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pagamentos_venda', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pagamentos_venda_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pagamentos_venda_venda_id'), ['venda_id'], unique=False)

    op.create_table('produtos_venda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venda_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=True),
    sa.Column('tipo_produto', sa.Enum('CADASTRADO', 'AVULSO', name='tipoprodutovenda'), nullable=False),
    sa.Column('descricao_avulsa', sa.String(length=255), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('valor_unitario', sa.Integer(), nullable=False),
    sa.Column('desconto', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Integer(), nullable=False),
    sa.CheckConstraint("((tipo_produto = 'CADASTRADO') AND (produto_id IS NOT NULL)) OR ((tipo_produto = 'AVULSO') AND (descricao_avulsa IS NOT NULL) AND (produto_id IS NULL))", name='ck_produto_venda_tipo_referencia_consistente'),
    sa.CheckConstraint('(produto_id IS NOT NULL) OR (descricao_avulsa IS NOT NULL)', name='ck_produto_venda_referencia_obrigatoria'),
    sa.CheckConstraint('desconto >= 0', name='ck_produto_venda_desconto_nao_negativo'),
    sa.CheckConstraint('quantidade > 0', name='ck_produto_venda_qtd_positiva'),
    sa.CheckConstraint('valor_unitario >= 0', name='ck_produto_venda_valor_unitario_nao_negativo'),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['venda_id'], ['vendas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('produtos_venda', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_produtos_venda_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_produtos_venda_venda_id'), ['venda_id'], unique=False)

    with op.batch_alter_table('ordem_servico_itens', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_ordem_servico_itens_produto_id'), type_='foreignkey')
        batch_op.create_foreign_key('fk_ordem_servico_itens_produto_id', 'produtos', ['produto_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordem_servico_itens', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_ordem_servico_itens_produto_id'), 'produtos', ['produto_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('produtos_venda', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_produtos_venda_venda_id'))
        batch_op.drop_index(batch_op.f('ix_produtos_venda_id'))

    op.drop_table('produtos_venda')
    with op.batch_alter_table('pagamentos_venda', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pagamentos_venda_venda_id'))
        batch_op.drop_index(batch_op.f('ix_pagamentos_venda_id'))

    op.drop_table('pagamentos_venda')
    with op.batch_alter_table('logs_produto', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_logs_produto_produto_id'))
        batch_op.drop_index(batch_op.f('ix_logs_produto_id'))

    op.drop_table('logs_produto')
    with op.batch_alter_table('vendas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendas_id'))
        batch_op.drop_index(batch_op.f('ix_vendas_funcionario_id'))
        batch_op.drop_index(batch_op.f('ix_vendas_cliente_id'))

    op.drop_table('vendas')
    with op.batch_alter_table('sessao_caixa', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessao_caixa_id'))
        batch_op.drop_index(batch_op.f('ix_sessao_caixa_funcionario_id'))

    op.drop_table('sessao_caixa')
    # ### end Alembic commands ###
