"""adiciona informações de fornecedores e produtos

Revision ID: 6b6dda97d4a0
Revises: a3b1c2d4e5f6
Create Date: 2026-05-26 21:24:56.084273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b6dda97d4a0'
down_revision: Union[str, Sequence[str], None] = 'a3b1c2d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movimentacoes_estoque',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('produto_nome', sa.String(length=255), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('usuario_nome', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.Enum('ENTRADA', 'SAIDA', 'AJUSTE', name='movimentacaotipo'), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('quantidade_anterior', sa.Integer(), nullable=False),
    sa.Column('quantidade_posterior', sa.Integer(), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('movimentacoes_estoque', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movimentacoes_estoque_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimentacoes_estoque_produto_id'), ['produto_id'], unique=False)

    with op.batch_alter_table('fornecedores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('cpf', sa.String(length=11), nullable=True))
        batch_op.add_column(sa.Column('veiculo', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('placa', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('observacao', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('banco', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('agencia', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('conta', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('tipo_conta', sa.Enum('POUPANCA', 'CORRENTE', name='bankaccounttype'), nullable=True))
        batch_op.add_column(sa.Column('pix', sa.String(length=150), nullable=True))
        batch_op.alter_column('cnpj',
               existing_type=sa.VARCHAR(length=14),
               nullable=True)
        batch_op.alter_column('nome_fantasia',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.create_unique_constraint('uq_fornecedores_cpf', ['cpf'])

    with op.batch_alter_table('vendas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_venda_numero_venda'))
        batch_op.drop_index(batch_op.f('uq_venda_numero_venda'))
        batch_op.create_index(batch_op.f('ix_vendas_numero_venda'), ['numero_venda'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendas_numero_venda'))
        batch_op.create_index(batch_op.f('uq_venda_numero_venda'), ['numero_venda'], unique=1)
        batch_op.create_index(batch_op.f('ix_venda_numero_venda'), ['numero_venda'], unique=False)

    with op.batch_alter_table('fornecedores', schema=None) as batch_op:
        batch_op.drop_constraint('uq_fornecedores_cpf', type_='unique')
        batch_op.alter_column('nome_fantasia',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('cnpj',
               existing_type=sa.VARCHAR(length=14),
               nullable=False)
        batch_op.drop_column('pix')
        batch_op.drop_column('tipo_conta')
        batch_op.drop_column('conta')
        batch_op.drop_column('agencia')
        batch_op.drop_column('banco')
        batch_op.drop_column('observacao')
        batch_op.drop_column('placa')
        batch_op.drop_column('veiculo')
        batch_op.drop_column('cpf')
        batch_op.drop_column('tipo')

    with op.batch_alter_table('movimentacoes_estoque', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movimentacoes_estoque_produto_id'))
        batch_op.drop_index(batch_op.f('ix_movimentacoes_estoque_id'))

    op.drop_table('movimentacoes_estoque')
    # ### end Alembic commands ###