"""adiciona tabela configuracoes_licenca

Revision ID: 706b2c881cab
Revises: 4600c632fe9b
Create Date: 2026-06-23 18:16:02.510199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '706b2c881cab'
down_revision: Union[str, Sequence[str], None] = '4600c632fe9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracoes_licenca',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.String(length=36), nullable=False),
    sa.Column('hwid', sa.String(length=255), nullable=False),
    sa.Column('licenca_id', sa.String(length=36), nullable=False),
    sa.Column('chave_ativacao', sa.Text(), nullable=False),
    sa.Column('session_key', sa.Text(), nullable=False),
    sa.Column('limite', sa.Integer(), nullable=False),
    sa.Column('data_vencimento', sa.DateTime(), nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('ultima_sinc', sa.DateTime(), nullable=False),
    sa.Column('grace_period', sa.Integer(), nullable=False),
    sa.Column('proxima_validacao', sa.DateTime(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('licenca_id')
    )
    with op.batch_alter_table('configuracoes_licenca', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_configuracoes_licenca_hwid'), ['hwid'], unique=True)
        batch_op.create_index(batch_op.f('ix_configuracoes_licenca_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuracoes_licenca', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_configuracoes_licenca_id'))
        batch_op.drop_index(batch_op.f('ix_configuracoes_licenca_hwid'))

    op.drop_table('configuracoes_licenca')
    # ### end Alembic commands ###
