"""criando_tabelas_orcamento_e_atualizando_vendas

Revision ID: 95cf25d1ca1f
Revises: b4c5d6e7f8a9
Create Date: 2026-06-01 14:52:29.931318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95cf25d1ca1f'
down_revision: Union[str, Sequence[str], None] = 'b4c5d6e7f8a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Clean up partial runs: drop tables if they already exist from a failed attempt
    op.execute(sa.text("DROP TABLE IF EXISTS orcamentos_produtos"))
    op.execute(sa.text("DROP TABLE IF EXISTS orcamentos"))

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orcamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('funcionario_id', sa.Integer(), nullable=False),
    sa.Column('venda_id', sa.Integer(), nullable=True),
    sa.Column('convertido', sa.Boolean(), nullable=False),
    sa.Column('observacao', sa.String(length=500), nullable=True),
    sa.Column('subtotal', sa.Integer(), nullable=False),
    sa.Column('entrega', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.CheckConstraint('entrega >= 0', name='ck_orcamento_entrega_nao_negativo'),
    sa.CheckConstraint('subtotal >= 0', name='ck_orcamento_subtotal_nao_negativo'),
    sa.CheckConstraint('total >= 0', name='ck_orcamento_total_nao_negativo'),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionarios.id'], ),
    sa.ForeignKeyConstraint(['venda_id'], ['vendas.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orcamentos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orcamentos_funcionario_id'), ['funcionario_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orcamentos_id'), ['id'], unique=False)

    op.create_table('orcamentos_produtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orcamento_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=True),
    sa.Column('tipo_produto', sa.Enum('CADASTRADO', 'AVULSO', name='tipoprodutovenda'), nullable=False),
    sa.Column('descricao_avulsa', sa.String(length=255), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('valor_unitario', sa.Integer(), nullable=False),
    sa.Column('desconto', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Integer(), nullable=False),
    sa.CheckConstraint("((tipo_produto = 'CADASTRADO') AND (produto_id IS NOT NULL)) OR ((tipo_produto = 'AVULSO') AND (descricao_avulsa IS NOT NULL) AND (produto_id IS NULL))", name='ck_orcamento_produto_tipo_referencia_consistente'),
    sa.CheckConstraint('(produto_id IS NOT NULL) OR (descricao_avulsa IS NOT NULL)', name='ck_orcamento_produto_referencia_obrigatoria'),
    sa.CheckConstraint('desconto >= 0', name='ck_orcamento_produto_desconto_nao_negativo'),
    sa.CheckConstraint('quantidade > 0', name='ck_orcamento_produto_qtd_positiva'),
    sa.CheckConstraint('valor_unitario >= 0', name='ck_orcamento_produto_valor_unitario_nao_negativo'),
    sa.ForeignKeyConstraint(['orcamento_id'], ['orcamentos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orcamentos_produtos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orcamentos_produtos_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orcamentos_produtos_orcamento_id'), ['orcamento_id'], unique=False)

    # Migrate existing ORCAMENTO status to ATIVA
    op.execute(sa.text("UPDATE vendas SET status = 'ATIVA' WHERE status = 'ORCAMENTO'"))

    with op.batch_alter_table('vendas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendas_numero_venda'))
        batch_op.drop_column('numero_venda')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numero_venda', sa.INTEGER(), nullable=True))
        batch_op.create_index(batch_op.f('ix_vendas_numero_venda'), ['numero_venda'], unique=1)

    with op.batch_alter_table('orcamentos_produtos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orcamentos_produtos_orcamento_id'))
        batch_op.drop_index(batch_op.f('ix_orcamentos_produtos_id'))

    op.drop_table('orcamentos_produtos')
    with op.batch_alter_table('orcamentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orcamentos_id'))
        batch_op.drop_index(batch_op.f('ix_orcamentos_funcionario_id'))

    op.drop_table('orcamentos')
    # ### end Alembic commands ###
