"""adiciona tabela terminais_conectados

Revision ID: a978a58b6d5d
Revises: b9d395c75856
Create Date: 2026-07-10 22:58:45.729766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a978a58b6d5d'
down_revision: Union[str, Sequence[str], None] = 'b9d395c75856'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('terminais_conectados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hwid', sa.String(length=255), nullable=False),
    sa.Column('ultima_sinc', sa.DateTime(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('terminais_conectados', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_terminais_conectados_hwid'), ['hwid'], unique=True)
        batch_op.create_index(batch_op.f('ix_terminais_conectados_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('terminais_conectados', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_terminais_conectados_id'))
        batch_op.drop_index(batch_op.f('ix_terminais_conectados_hwid'))

    op.drop_table('terminais_conectados')
    # ### end Alembic commands ###
